update ""data clean"" hatası çözümü:

hata alınan server içine girilir
hata alınan servisi görmek için servisler listelenir:docker service ls
hata alınan servisin loglarına bakılır:docker service logs .....
o an ki hata :  "opperational error:connection to server socket"
hata alınan servisin içine bakılır:docker service inspect ......
environment leri eksik ise sonraki adımlar izlenir.
ilgili yml dosyalarının olduğu dizine gidilir
yml dosyasının içine girilir: cat ""docker-compose.yml""
ilgili yml dosyalarına environment'ler eklenir(biz bi tane ana yml dosyasına ve 2 tane ayrı yml dosyasına ekledik)
yml dosyalarının içindeki imajlar son alınan imaj olarak değiştirilir
ilgili yml dosyaları düzeltildikten sonra ilgili servisler silinir:docker service rm ""trafik_dataclean"" ""trafik_kkngroup""
sonra tekrardan servisleri çalıştırmak için :docker stack deploy -c ""docker-compose-kkn-dataclean.yml"" ""trafik""
imajı pull edemediğini anladığımız için tekrardan elimizle pull ettik:decker pull ""geoanka/trafik-python-kkngroup:Dev721""
docker service ls ile tekradan replicas ları kontrol ettik ve sorun çözüldü.
